//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCoursework.Site.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IGuestService")]
    public interface IGuestService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuestService/GetData", ReplyAction="http://tempuri.org/IGuestService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuestService/GetData", ReplyAction="http://tempuri.org/IGuestService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuestService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IGuestService/GetDataUsingDataContractResponse")]
        ServiceCoursework.Services.CompositeType GetDataUsingDataContract(ServiceCoursework.Services.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuestService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IGuestService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ServiceCoursework.Services.CompositeType> GetDataUsingDataContractAsync(ServiceCoursework.Services.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGuestServiceChannel : ServiceCoursework.Site.ServiceReference.IGuestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GuestServiceClient : System.ServiceModel.ClientBase<ServiceCoursework.Site.ServiceReference.IGuestService>, ServiceCoursework.Site.ServiceReference.IGuestService {
        
        public GuestServiceClient() {
        }
        
        public GuestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GuestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ServiceCoursework.Services.CompositeType GetDataUsingDataContract(ServiceCoursework.Services.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ServiceCoursework.Services.CompositeType> GetDataUsingDataContractAsync(ServiceCoursework.Services.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
